/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LessonsDayRouteImport } from './routes/lessons.$day'
import { Route as CertificatesCodeRouteImport } from './routes/certificates.$code'
import { Route as ApiAvatarRouteImport } from './routes/api.avatar'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminMeetingsRouteImport } from './routes/admin.meetings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminHomeworkRouteImport } from './routes/admin.homework'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LessonsDayRoute = LessonsDayRouteImport.update({
  id: '/lessons/$day',
  path: '/lessons/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCodeRoute = CertificatesCodeRouteImport.update({
  id: '/certificates/$code',
  path: '/certificates/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMeetingsRoute = AdminMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeworkRoute = AdminHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/homework': typeof AdminHomeworkRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/lessons/$day': typeof LessonsDayRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/homework': typeof AdminHomeworkRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/lessons/$day': typeof LessonsDayRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/homework': typeof AdminHomeworkRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/lessons/$day': typeof LessonsDayRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contacts'
    | '/dashboard'
    | '/offer'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/admin/homework'
    | '/admin/lessons'
    | '/admin/login'
    | '/admin/meetings'
    | '/admin/students'
    | '/api/avatar'
    | '/certificates/$code'
    | '/lessons/$day'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacts'
    | '/dashboard'
    | '/offer'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/admin/homework'
    | '/admin/lessons'
    | '/admin/login'
    | '/admin/meetings'
    | '/admin/students'
    | '/api/avatar'
    | '/certificates/$code'
    | '/lessons/$day'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contacts'
    | '/dashboard'
    | '/offer'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/admin/homework'
    | '/admin/lessons'
    | '/admin/login'
    | '/admin/meetings'
    | '/admin/students'
    | '/api/avatar'
    | '/certificates/$code'
    | '/lessons/$day'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  OfferRoute: typeof OfferRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  CertificatesCodeRoute: typeof CertificatesCodeRoute
  LessonsDayRoute: typeof LessonsDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lessons/$day': {
      id: '/lessons/$day'
      path: '/lessons/$day'
      fullPath: '/lessons/$day'
      preLoaderRoute: typeof LessonsDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$code': {
      id: '/certificates/$code'
      path: '/certificates/$code'
      fullPath: '/certificates/$code'
      preLoaderRoute: typeof CertificatesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meetings': {
      id: '/admin/meetings'
      path: '/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AdminMeetingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homework': {
      id: '/admin/homework'
      path: '/homework'
      fullPath: '/admin/homework'
      preLoaderRoute: typeof AdminHomeworkRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminHomeworkRoute: typeof AdminHomeworkRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMeetingsRoute: typeof AdminMeetingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHomeworkRoute: AdminHomeworkRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMeetingsRoute: AdminMeetingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  OfferRoute: OfferRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  CertificatesCodeRoute: CertificatesCodeRoute,
  LessonsDayRoute: LessonsDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
