create table if not exists public.archie_settings (
  id boolean primary key default true check (id),
  enabled boolean not null default false,
  name text not null default 'Арчи',
  subtitle text not null default 'Помощник курса',
  welcome_message text not null default 'Привет! Я Арчи. Помогу разобраться в материале этого урока.',
  system_prompt text not null default '',
  max_message_length integer not null default 1500 check (max_message_length between 100 and 6000),
  max_history_messages integer not null default 8 check (max_history_messages between 0 and 20),
  rate_limit_per_minute integer not null default 8 check (rate_limit_per_minute between 1 and 60),
  timeout_ms integer not null default 30000 check (timeout_ms between 5000 and 60000),
  quick_actions_enabled boolean not null default true,
  provider text not null default 'openrouter' check (provider in ('openrouter', 'openai', 'deepseek', 'custom')),
  base_url text not null default 'https://openrouter.ai/api/v1',
  model text not null default '',
  encrypted_api_key text,
  api_key_mask text not null default '',
  connection_status text not null default 'unknown' check (connection_status in ('unknown', 'connected', 'error')),
  connection_checked_at timestamptz,
  connection_error text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into public.archie_settings (id) values (true) on conflict (id) do nothing;

create table if not exists public.archie_request_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  lesson_id uuid references public.lessons(id) on delete set null,
  provider text not null,
  model text not null,
  status text not null check (status in ('success', 'error')),
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  created_at timestamptz not null default now()
);

create index if not exists archie_request_stats_created_at_idx
  on public.archie_request_stats (created_at desc);
create index if not exists archie_request_stats_user_created_idx
  on public.archie_request_stats (user_id, created_at desc);

alter table public.archie_settings enable row level security;
alter table public.archie_request_stats enable row level security;
revoke all on public.archie_settings from anon, authenticated;
revoke all on public.archie_request_stats from anon, authenticated;
grant all on public.archie_settings to service_role;
grant all on public.archie_request_stats to service_role;
grant usage, select on sequence public.archie_request_stats_id_seq to service_role;
